// Моки для API функций
export const getIngredientsApi = jest.fn();
export const getFeedsApi = jest.fn();
export const getOrdersApi = jest.fn();
export const getOrderByNumberApi = jest.fn();
export const orderBurgerApi = jest.fn();
export const loginUserApi = jest.fn();
export const registerUserApi = jest.fn();
export const getUserApi = jest.fn();
export const updateUserApi = jest.fn();
export const logoutApi = jest.fn();
